### ISSUE TITLE
Use @sensenet/hooks-react instead of own implementation

### ISSUE THREAD

**Issue by B3zo0** [sn-panda/snmemoapp#6]
:watch:
estimate:
time spent:
_________

With the release of @sensenet/hooks-react package, you can use the useRepository hook from there. 

- [x] Remove the current use-repository.ts
- [x] Add @sensenet/hooks-react to package.json
- [x] Refactor code to use useRepository from there

**Comment by blaskodaniel** [comment]
I create a pull request for this issue: https://github.com/sn-panda/snmemoapp/pull/9
